apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.component_id }}
  description: Kafka Topic ${{ values.kafkaTopicName }}
  tags:
    - kafka
    - topic
  annotations:
    'kafka.apache.org/topic-name': ${{ values.kafkaTopicName }}
    'backstage.io/managed-by-location': 'template:create-kafka-topic'
spec:
  type: kafka-topic
  owner: ${{ values.owner }}
  system: default
