apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    bitbucket.org/project-slug: ${{ values.bbWorkspace }}/${{ values.bbRepo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: Component
  lifecycle: experimental
  owner: ${{values.owner | dump}}
