apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: create-kafka-topic
  title: Create New Kafka Topic
  description: Creates a new Kafka topic and registers it as a Resource entity.
  tags:
    - kafka
    - topic
    - resource
spec:
  owner: user:default/guest # Set a sensible default owner
  type: service
  
  parameters:
    - title: Provide Component Information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Topic Resource ID
          type: string
          description: Unique, short ID for the new topic resource (e.g., 'payment-topic-dev')
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
          description: Owner of the new topic resource
          
    - title: Provide Kafka Topic Details
      required:
        - kafkaTopicName
        - partitions
      properties:
        kafkaTopicName:
          title: Kafka Topic Name
          type: string
          description: The exact topic name to be created on the broker (e.g., 'com.aoins.payments')
        partitions:
          title: Partition Count
          type: number
          default: 3
          description: Number of partitions for the topic
          
  steps:
    # 1. FETCH AND RENDER: Fetches the skeleton, rendering the component-info.yaml
    - id: fetch-template
      name: Fetching Template Files
      action: fetch:template
      input:
        url: ./skeleton # Assumes your skeleton is in a subfolder named 'skeleton'

    # 2. CREATE TOPIC: Executes the Kafka Scaffolder action
    - id: create-topic
      name: Creating Kafka Topic on Broker
      action: kafka:create-topic 
      input:
        topic: ${{ values.kafkaTopicName }}
        partitions: ${{ values.partitions }}
        # NOTE: If you need to specify a broker, add the input here:
        # broker: my-kafka-broker 
        
    # 3. REGISTER ENTITY: Registers the component-info.yaml which is now fully rendered
    - id: register-component
      name: Registering Topic Resource in Catalog
      action: catalog:register
      input:
        # This registers the file that was rendered in the 'fetch-template' step
        url: ./component-info.yaml 
        
  output:
    links:
      - title: Catalog Entity
        icon: catalog
        entityRef: "resource:default/${{ values.component_id }}"
